package magicchief.main.brewersservant

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

class DBHelper (context: Context): SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {

    override fun onCreate(db: SQLiteDatabase) {
        // Define SQL instructions
        // Create Card table
        val createCardDB = (
                "CREATE TABLE $CARD_TABLE_NAME ("
                        + ")"
                )
        // Create CardFace table
        val createCardFaceDB = (
                "CREATE TABLE $CARD_FACE_TABLE_NAME ("
                        + ")"
                )
        // Create RelatedCard table
        val createRelatedCardDB = (
                "CREATE TABLE $RELATED_CARD_TABLE_NAME ("
                        + ")"
                )
        // Create CardSet table
        val createCardSetDB = (
                "CREATE TABLE $CARD_SET_TABLE_NAME ("
                        + ")"
                )

        // Execute SQL code
        db.execSQL(createCardDB)
        db.execSQL(createCardFaceDB)
        db.execSQL(createRelatedCardDB)
        db.execSQL(createCardSetDB)
    }

    override fun onUpgrade(db: SQLiteDatabase, p1: Int, p2: Int) {
        // This method drops the tables if they existed and creates them again
        db.execSQL("DROP TABLE IF EXISTS $CARD_TABLE_NAME")
        db.execSQL("DROP TABLE IF EXISTS $CARD_FACE_TABLE_NAME")
        db.execSQL("DROP TABLE IF EXISTS $RELATED_CARD_TABLE_NAME")
        db.execSQL("DROP TABLE IF EXISTS $CARD_SET_TABLE_NAME")

        onCreate(db)
    }

    companion object {
        // Database variables

        // Database name
        private val DATABASE_NAME = "PaintersServantDB"

        // Database version
        private val DATABASE_VERSION = 1

        // Card table name
        private val CARD_TABLE_NAME = "Card"
        // Card table column names
        private val CARD_ID = "id"
        private val CARD_CMC = "cmc"
        private val CARD_COLOR_IDENTITY = "color_identity"
        private val CARD_COLORS = "colors"
        private val CARD_LAYOUT = "layout"
        private val CARD_LOYALTY = "loyalty"
        private val CARD_MANA_COST = "mana_cost"
        private val CARD_NAME = "name"
        private val CARD_ORACLE_TEXT = "oracle_text"
        private val CARD_POWER = "power"
        private val CARD_PRODUCED_MANA = "produced_mana"
        private val CARD_TOUGHNESS = "toughness"
        private val CARD_TYPE_LINE = "type_line"
        private val CARD_ARTIST = "artist"
        private val CARD_FLAVOR_TEXT = "flavor_text"
        private val CARD_RARITY = "rarity"
        private val CARD_SET_ID = "set_id"
        private val CARD_PRICE_USD = "price_usd"
        private val CARD_PRICE_EUR = "price_eur"
        private val CARD_PRICE_TIX = "price_tix"
        private val CARD_LEGAL_STANDARD = "legal_standard"
        private val CARD_LEGAL_PIONEER = "legal_pioneer"
        private val CARD_LEGAL_MODERN = "legal_modern"
        private val CARD_LEGAL_LEGACY = "legal_legacy"
        private val CARD_LEGAL_VINTAGE = "legal_vintage"
        private val CARD_LEGAL_BRAWL = "legal_brawl"
        private val CARD_LEGAL_HISTORIC = "legal_historic"
        private val CARD_LEGAL_PAUPER = "legal_pauper"
        private val CARD_LEGAL_PENNY = "legal_penny"
        private val CARD_LEGAL_COMMANDER = "legal_commander"
        private val CARD_IMAGE_PNG = "image_png"
        private val CARD_IMAGE_BORDER_CROP = "image_border_crop"
        private val CARD_IMAGE_ART_CROP = "image_art_crop"
        private val CARD_IMAGE_LARGE = "image_large"
        private val CARD_IMAGE_NORMAL = "image_normal"
        private val CARD_IMAGE_SMALL = "image_small"

        // CardFace table name
        private val CARD_FACE_TABLE_NAME = "CardFace"
        // CardFace table column names
        private val CARD_FACE_ID = "id" // Autogenerated
        private val CARD_FACE_ID_MAIN_CARD = "id_main_card"
        private val CARD_FACE_ARTIST = "artist"
        private val CARD_FACE_CMC = "cmc"
        private val CARD_FACE_COLORS = "colors"
        private val CARD_FACE_FLAVOR_TEXT = "flavor_text"
        private val CARD_FACE_LAYOUT = "layout"
        private val CARD_FACE_LOYALTY = "loyalty"
        private val CARD_FACE_MANA_COST = "mana_cost"
        private val CARD_FACE_NAME = "name"
        private val CARD_FACE_ORACLE_TEXT = "oracle_text"
        private val CARD_FACE_POWER = "power"
        private val CARD_FACE_TOUGHNESS = "toughness"
        private val CARD_FACE_TYPE_LINE = "type_line"
        private val CARD_FACE_IMAGE_PNG = "image_png"
        private val CARD_FACE_IMAGE_BORDER_CROP = "image_border_crop"
        private val CARD_FACE_IMAGE_ART_CROP = "image_art_crop"
        private val CARD_FACE_IMAGE_LARGE = "image_large"
        private val CARD_FACE_IMAGE_NORMAL = "image_normal"
        private val CARD_FACE_IMAGE_SMALL = "image_small"

        // RelatedCard table name
        private val RELATED_CARD_TABLE_NAME = "RelatedCard"
        // RelatedCard table column names
        private val RELATED_CARD_ID_MAIN = "id_main"
        private val RELATED_CARD_ID_RELATED = "id_related"
        private val RELATED_CARD_COMPONENT = "component"

        // CardSet table name
        private val CARD_SET_TABLE_NAME = "CardSet"
        // CardSet table column names
        private val CARD_SET_SET_ID = "id"
        private val CARD_SET_CODE = "code"
        private val CARD_SET_NAME = "name"
        private val CARD_SET_ICON_SVG_URL = "icon_svg_uri"

    }
}